### ISSUE TITLE
what are your results?

### ISSUE THREAD

**Issue by franchesoni** [zshn25/DINOv2_mmseg#2]
Hi! 

Did you manage to reproduce the results on the paper?

I find the repo potentially very useful, thanks for sharing.

**Comment by zshn25** [comment]
Hi, thanks for your interest, we weren't exactly able to replicate the paper's result but we got close.

For ADE20K dataset, without TTA, these are our resulting metrics

`aAcc: 82.1200,  mIoU: 48.9400,  mAcc: 61.2500`

The reported mIoU was **51.3**

**Comment by franchesoni** [comment]
thanks! will let you know if I manage to get that 2.4% back :)

**Comment by franchesoni** [comment]
from the paper, the results are using TTA. This should be fine
> +ms: a boosted version of the linear setup. We concatenate the patch tokens of the 4 last layers, use a larger image resolution of 640, and use multiscale test-time augmentations to improve the predictions.
