### ISSUE TITLE
No pre-training weights file found

### ISSUE THREAD

**Issue by yuyu19970716** [zshn25/DINOv2_mmseg#3]
Hello, thank you very much for your contribution, I would like to ask you about work_dirs/dinov2_vitb14_cityscapes_ms_config/cleaned_epoch_120.pth in segmentation.ipynb. I didn't find this weight file, can you tell me where to download it?

**Comment by zshn25** [comment]
Hi, thanks for your interest. We currently do not plan to upload the downstream heads. Feel free to open a PR if you've trained one.

**Comment by yuyu19970716** [comment]
Thank you very much for the restoration,but  I'm so sorry, I don't understand what the PR you are talking about, and the init_cfg=dict(type='Pretrained', checkpoint=".. in the code. /prototyping_dinov2/model.pth"), is there a download path for this?I'm now ready to download the Cityspaces dataset myself to train the network

**Comment by zshn25** [comment]
The pretrained checkpoint is same as the DINOv2 backbones https://github.com/facebookresearch/dinov2?tab=readme-ov-file#pretrained-models. You can use one of those there. Best regards

**Comment by yuyu19970716** [comment]
Okay, thank you very much and good luck!
