### ISSUE TITLE
Questions about training other datasets

### ISSUE THREAD

**Issue by yuyu19970716** [zshn25/DINOv2_mmseg#4]
Hello, how should I modify the configuration file if I want to train on a medical dataset, such as pannuke, instead of training on a cityspaces dataset? Do I just need to have the image of train/test/val and the corresponding label image?

**Comment by MyHogsmeade** [comment]
> Hello, how should I modify the configuration file if I want to train on a medical dataset, such as pannuke, instead of training on a cityspaces dataset? Do I just need to have the image of train/test/val and the corresponding label image?

Did you succeed? I have a similar need to replace the data set. Can you give me some suggestions?
